# Generated by Django 5.0.6 on 2024-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen_url', models.URLField(verbose_name='imagen_url')),
                ('ean', models.IntegerField(unique=True, verbose_name='ean')),
            ],
        ),
    ]
