# Generated by Django 5.0.6 on 2024-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ean',
            field=models.BigIntegerField(unique=True, verbose_name='ean'),
        ),
    ]
